name: Create Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Install Packer
      uses: hashicorp/setup-packer@main
      with:
        packer_version: '1.7.2'

    - name: Run Packer
      run: |
        packer build template.json

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: custom-image
        path: output/*
